layout_spectrum: 0.6231028
name: FUSEBO
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.625359711702913
  saturation: 0.8494143839925528
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  lightness: 0.1286011955235153
  rhythmicContrast: 0.915904491674155
typography_spectrum: 0.185175035148859
